networks:
  dream-network:
    driver: bridge

volumes:
  pgdata:

services:
  db:
    image: postgres:15
    container_name: pg-db
    environment:
      POSTGRES_DB: dreamvacations
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Biggie@44
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - dream-network

  backend:
    image: kelomi44/dream-backend:latest
    container_name: backend
    environment:
      DB_NAME: dreamvacations
      DB_USER: postgres
      DB_PASSWORD: Biggie@44
      DB_HOST: db
      DB_PORT: 5432
      PORT: 3001
      COUNTRIES_API_BASE_URL: https://restcountries.com/v3.1
    depends_on:
      - db
    ports:
      - "3001:3001"
    networks:
      - dream-network

  frontend:
    image: kelomi44/dream-frontend:latest
    container_name: frontend
    environment:
      - REACT_APP_API_URL=http://backend:3001
    depends_on:
      - backend
    ports:
      - "3000:80"
    networks:
      - dream-network
